services:
  fs_postgres:
    build: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -U postgres
  fs_backend:
    build: backend
    ports:
      - "5000:5000"
    links:
      - fs_postgres
    environment:
      POSTGRES_HOST: fs_postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: default
      POSTGRES_DB: master
      FLASK_ENV: development
      JWT_SECRET: "lifeisbigcat"
      EMAIL_USER: "uwfirststep@gmail.com"
      EMAIL_PASS: "skhcbyydtaiankse"

    volumes:
      - ./backend:/app
    depends_on:
      fs_postgres:
        condition: service_healthy
  fs_frontend:
    build: frontend
    ports:
      - "3000:3000"
    depends_on:
      - fs_backend