version: "3.9"
services:
  fs_backend:
    build: backend
    ports:
      - "5000:5000"
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432

  fs_postgres:
    image: "postgres:latest"
    environment:
      - POSTGRES_PASSWORD=default
    ports:
      - "5432:5432"