version: "3.9"
services:
  fs_postgres:
    build: postgres
    ports:
      - "5432:5432"
  fs_backend:
    build: backend
    ports:
      - "5000:5000"
    links:
      - fs_postgres
    environment:
      POSTGRES_HOST: fs_postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: default
      POSTGRES_DB: master
      FLASK_ENV: development
    volumes:
      - ./backend:/app
  fs_frontend:
    build: frontend
    ports:
      - "3000:3000"
    depends_on:
      - fs_backend