# SKILLSET IDS
EMBEDDED_SOFTWARE_ID = 1
DISTRIBUTED_SYSTEMS_ID = 2
DATABASE_SYSTEMS_ID = 3
HARDWARE_ID = 4
LEADERSHIP_ID = 5
TECHNICAL_WRITING_ID = 6

# GROUP MATCHING PARAMETERS
MAX_GROUP_SIZE = 5
MIN_GROUP_SIZE = 4
